services:
  backend:
    build: ./backend
    ports:
      - "5190:5190"
    environment:
      - ASPNETCORE_URLS=http://+:5190
    networks:
      - webnet

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.docker
    networks:
      - webnet

networks:
  webnet:
