name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-backend:
    name: Build & Test .NET Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./backend/Webjet.sln

      - name: Build
        run: dotnet build --no-restore ./backend/Webjet.sln

      - name: Run tests
        run: dotnet test --no-build --verbosity normal ./backend/Webjet.Tests/Webjet.Tests.csproj

  build-frontend:
    name: Build React Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Build React App
        run: cd frontend && npm run build
